version: "3"

vars:
  VERSION:
    sh: git rev-parse --short HEAD

env:
  BASE_APP_NAME: am-stats-update
  NAMESPACE: aftermath-services
  REGISTRY: us-east4-docker.pkg.dev/aftermath-327212/aftermath-images
  K8S_TYPE: Deployment

tasks:
  build-worker:
    desc: Build, tag and load the image. Add '-- load' to load into docker.
    env:
      FLAVOR: worker
    cmds:
      - docker buildx build --platform linux/amd64 -f Dockerfile.$FLAVOR -t $REGISTRY/$BASE_APP_NAME-$FLAVOR:{{.VERSION}} -t $REGISTRY/$BASE_APP_NAME-$FLAVOR:latest --{{.CLI_ARGS | default "push"}} --secret id=ssh_priv,src=$HOME/.ssh/id_rsa --secret id=ssh_pub,src=$HOME/.ssh/id_rsa.pub .

  build-scheduler:
    desc: Build, tag and load the image. Add '-- load' to load into docker.
    env:
      FLAVOR: scheduler
    cmds:
      - docker buildx build --platform linux/amd64 -f Dockerfile.$FLAVOR -t $REGISTRY/$BASE_APP_NAME-$FLAVOR:{{.VERSION}} -t $REGISTRY/$BASE_APP_NAME-$FLAVOR:latest --{{.CLI_ARGS | default "push"}} --secret id=ssh_priv,src=$HOME/.ssh/id_rsa --secret id=ssh_pub,src=$HOME/.ssh/id_rsa.pub .

  build:
    desc: Build, tag and load the image. Add '-- load' to load into docker.
    cmds:
      - task: build-worker
      - task: build-scheduler

  restart-worker:
    desc: Restart k8s deployment
    env:
      APP_NAME: "{{.BASE_APP_NAME}}-worker"
    cmds:
      - kubectl rollout restart $K8S_TYPE/$APP_NAME -n $NAMESPACE

  restart-scheduler:
    desc: Restart k8s deployment
    env:
      APP_NAME: "{{.BASE_APP_NAME}}-scheduler"
    cmds:
      - kubectl rollout restart $K8S_TYPE/$APP_NAME -n $NAMESPACE

  restart:
    desc: Restart k8s deployment for worker and scheduler
    cmds:
      - task: restart-worker
      - task: restart-scheduler
