version: "3"

vars:
  VERSION:
    sh: git rev-parse --short HEAD

env:
  BASE_APP_NAME: am-stats-update
  NAMESPACE: aftermath-services
  REGISTRY: us-east4-docker.pkg.dev/aftermath-327212/aftermath-images
  K8S_TYPE: Deployment

tasks:
  build:
    desc: Build, tag and load the image. Add '-- load' to load into docker.
    cmds:
      - docker buildx build --platform linux/amd64 -t $REGISTRY/$BASE_APP_NAME:{{.VERSION}} -t $REGISTRY/$BASE_APP_NAME:latest --{{.CLI_ARGS | default "push"}} --secret id=ssh_priv,src=$HOME/.ssh/id_rsa --secret id=ssh_pub,src=$HOME/.ssh/id_rsa.pub .

  restart:
    desc: Restart k8s deployment
    cmds:
      - kubectl rollout restart $K8S_TYPE/$BASE_APP_NAME -n $NAMESPACE
